columns:
    target: Outcome
    numerical: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age]
    zero_as_missing: [Glucose, BloodPressure, SkinThickness, Insulin, BMI]
    engineered_categorical: [NEW_AGE_CAT, NEW_BMI, NEW_GLUCOSE, NEW_AGE_BMI_NOM, NEW_AGE_GLUCOSE_NOM, NEW_INSULIN_SCORE]
    engineered_numerical: [NEW_GLUCOSE_X_INSULIN, NEW_GLUCOSE_X_PREGNANCIES]